import 'package:flutter/material.dart';
import 'package:nuox_project/pages/featured/services/featured_model.dart';
import 'package:nuox_project/pages/featured/widgets/small_item_card.dart';
import 'package:nuox_project/providers/auth_provider.dart';
import 'package:nuox_project/widgets/see_all_widget.dart';
import 'package:provider/provider.dart';
import '../../../../constants/constants.dart';
import '../../../../widgets/bold_heading.dart';
import '../../services/featured_provider.dart';
import '../top_courses_section/top_courses_section.dart';
import '../catagories_section/catagories_section.dart';
import '../../widgets/featured_item_card.dart';
import '../../widgets/see_all_page_featured.dart';

class FeaturedSection extends StatefulWidget {
  const FeaturedSection({super.key});

  @override
  State<FeaturedSection> createState() => _FeaturedSectionState();
}

class _FeaturedSectionState extends State<FeaturedSection> {
  @override
  void initState() {
    Provider.of<FeaturedProvider>(context, listen: false).sample();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final featuredProvider = Provider.of<FeaturedProvider>(context);
    //featuredProvider.Sample();
    final size = MediaQuery.of(context).size.width;
    return featuredProvider.isLoading == true
        ? Center(child: CircularProgressIndicator())
        : Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              KHeight15,
              const BoldHeading(
                heading: "Featured",
              ),
              SizedBox(
                height: size * .68,
                child: SingleChildScrollView(
                  physics: const BouncingScrollPhysics(),
                  scrollDirection: Axis.horizontal,
                  child: Row(
                    children: [
                      ListView.builder(
                        shrinkWrap: true,
                        physics: const BouncingScrollPhysics(),
                        itemCount: featuredProvider.auto.length,
                        scrollDirection: Axis.horizontal,
                        itemBuilder: (context, index) {
                          final Autogenerated data =
                              featuredProvider.auto[index]!;
                          return SmallItemCard(
                              rating: data.rating!.toDouble(),
                              image: data.thumbnail!.full_size.toString(),
                              authorName: featuredProvider
                                  .auto[index]!.courseName
                                  .toString(),
                              courseName: data.instructor!.name.toString(),
                              coursePrice: data.price!);
                        },
                      ),
                      KWidth30,
                      GestureDetector(
                        child: const SeeAllWidget(),
                        onTap: () {
                          featuredProvider.sample();
                          Navigator.of(context).push(MaterialPageRoute(
                              builder: (context) => SeeAllPageFeatured()));
                        },
                      ),
                      KWidth30
                    ],
                  ),
                ),
              ),
              KHeight20,
              CatagoriesSection(),
              KHeight20,
              TopCoursesSection(),
            ],
          );
  }
}
