class Autogenerated {
  int? id;
  String? courseName;
  double? price;
  String? offerPrice;
  SubCategory? subCategory;
  String? createdAt;
  String? updatedAt;
  bool? featuredCourse;
  bool? recommendedCourse;
  Thumbnail? thumbnail;
  Instructor? instructor;
  String? introVideo;
  int? rating;
  int? ratingCount;
  bool? isWishList;

  Autogenerated(
      {this.isWishList,
      this.id,
      this.courseName,
      this.price,
      this.offerPrice,
      this.subCategory,
      this.createdAt,
      this.updatedAt,
      this.featuredCourse,
      this.recommendedCourse,
      this.thumbnail,
      this.instructor,
      this.introVideo,
      this.rating,
      this.ratingCount});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    isWishList = json['wish_list'];
    ratingCount = json['rating_count'];
    id = json['id'];
    courseName = json['course_name'];
    price = json['price'];
    offerPrice = json['offer_price'];
    subCategory = json['sub_category'] != null
        ? SubCategory.fromJson(json['sub_category'])
        : null;
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    featuredCourse = json['featured_course'];
    recommendedCourse = json['recommended_course'];
    thumbnail = json['thumbnail'] != null
        ? Thumbnail.fromJson(json['thumbnail'])
        : null;
    instructor = json['instructor'] != null
        ? Instructor.fromJson(json['instructor'])
        : null;
    if (json['intro_video'] != null) {
      introVideo = json['intro_video'];
    }
    rating = json['rating'];
  }
}

class SubCategory {
  int? id;
  String? subCatehoryName;
  int? category;

  SubCategory({this.id, this.subCatehoryName, this.category});

  SubCategory.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    subCatehoryName = json['sub_catehory_name'];
    category = json['category'];
  }
}

class Thumbnail {
  String? thumbnail;
  String? full_size;

  Thumbnail({this.thumbnail, this.full_size});

  Thumbnail.fromJson(Map<String, dynamic> json) {
    thumbnail = json['thumbnail'];
    full_size = json['full_size'];
  }
}

class Instructor {
  String? name;
  ProfilePic? profilePic;
  String? phone;
  String? email;
  String? details;

  Instructor(
      {this.name, this.profilePic, this.phone, this.email, this.details});

  Instructor.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    profilePic = json['profile_pic'] != null
        ? ProfilePic.fromJson(json['profile_pic'])
        : null;
    phone = json['phone'];
    email = json['email'];
    details = json['details'];
  }
}

class ProfilePic {
  String? thumbnail;
  String? fullSize;

  ProfilePic({this.thumbnail, this.fullSize});

  ProfilePic.fromJson(Map<String, dynamic> json) {
    thumbnail = json['thumbnail'];
    fullSize = json['full_size'];
  }
}
